### ISSUE TITLE
Airline Visual Mode Bug

### ISSUE THREAD

**Issue by tommyknows** [skielbasa/vim-material-monokai#6]
Hi,

I think I came across a bug in the color of the airline mode indicator:
in normal mode:
![normal_mode](https://user-images.githubusercontent.com/16387735/47079893-da5d8980-d206-11e8-8bb3-3a3d201da18d.png)

and insert mode:
![insert_mode](https://user-images.githubusercontent.com/16387735/47079908-dfbad400-d206-11e8-921a-d5c7eb918406.png)

I think these look how they should, but then there's this:
![visual_mode](https://user-images.githubusercontent.com/16387735/47079976-0b3dbe80-d207-11e8-8f89-4d3cf7cdd813.png)

Now, I don't know about the colour itself, but the problem here is that the errors at the right edge (there red and orange) change to what looks like non-24bit colours?

Now, I don't know if it's a bug in my vimrc (i tried to make it smaller, but it still could be that i missed something), or if it is a bug in the theme. Feel free to close if it is not :-)

**Comment by skielbasa** [comment]
I'm sure that's the theme, I fixed a similar issue already. I may have missed one of the modes last time. I'll take a look at that for you.

**Comment by skielbasa** [comment]
Sorry about the delay. Life got in the way (as it does). That is actually intentional. The warning orange is the same as the visual mode orange, so a the error red-orange is used for the warning and a red is used for the error when in visual mode.

There is actually a theme setting that sets it so only the mode indicator changes color `materialmonokai_subtle_airline`. This will leave the look of normal mode for the info/errors section regardless of mode (at the cost of a some glancability).

**Comment by tommyknows** [comment]
Ah, makes sense. Thanks for the explanation!
